name = "importer-webhook"
main = "index.ts"
workers_dev = true
compatibility_date = "2023-01-25"

[vars]
ORDERS_SHEET_ID = "1t7Wm14uTmUdVHrE3_D7lamqZCc8gbwyW70M1ixhlChg"
ORDERS_SHEET_RANGE = "stocks!A1:G1"

[[ d1_databases ]]
binding = "stocksDB"
database_name = "stocks_db"
database_id = "d520f908-e3d6-4ce4-a4b3-fcd831aa4106"
preview_database_id = "0e329d79-9c6b-4eee-895e-c5c9f865bd23"

[build]
command = "npm install"